#cloud-config
coreos:
  update:
    reboot-strategy: "off"
  etcd2:
    proxy: "on"
    listen-client-urls: "http://127.0.0.1:2379,http://127.0.0.1:4001"
    peer-trusted-ca-file: "/etc/kubernetes/tls/ca-chain.pem"
    peer-cert-file: "/etc/kubernetes/tls/etcd-client.pem"
    peer-key-file: "/etc/kubernetes/tls/etcd-client-key.pem"
    trusted-ca-file: "/etc/kubernetes/tls/ca-chain.pem"
    cert-file: "/etc/kubernetes/tls/etcd-client.pem"
    key-file: "/etc/kubernetes/tls/etcd-client-key.pem"
  flannel:
    interface: "$private_ipv4"
  units:
    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Wants=flanneld.service

        [Service]
        ExecStartPre=/usr/bin/systemctl is-active flanneld.service
        ExecStart=/opt/bin/kubelet-wrapper.sh
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
    - name: docker-gc.service
      content: |
        [Unit]
        Description=Cleanup docker images and volumes
        Requires=docker.service
        ConditionPathExists=/opt/bin/docker-gc.sh

        [Service]
        Type=simple
        ExecStart=/opt/bin/docker-gc.sh
    - name: docker-gc.timer
      command: start
      content: |
        [Unit]
        Description=Run docker-gc daily

        [Timer]
        OnCalendar=daily
        Unit=docker-gc.service
    - name: docker-logrotate.service
      content: |
        [Unit]
        Description=Rotate docker container logs
        Requires=docker.service
        ConditionPathExists=/etc/logrotate.d/docker-containers.conf

        [Service]
        Type=simple
        ExecStart=/usr/sbin/logrotate -f -v /etc/logrotate.d/docker-containers.conf
    - name: docker-logrotate.timer
      command: start
      content: |
        [Unit]
        Description=Rotate docker logs hourly

        [Timer]
        OnCalendar=hourly
        Unit=docker-logrotate.service
    - name: docker.service
      command: start
      drop-ins:
        - name: 10-docker-mount.conf
          content: |
            [Unit]
            After=var-lib-docker.mount
            Wants=var-lib-docker.mount
        - name: 20-opt-data-mount.conf
          content: |
            [Unit]
            After=opt-data.mount
            Wants=opt-data.mount
        - name: 30-opt-logging-mount.conf
          content: |
            [Unit]
            After=opt-logging.mount
            Wants=opt-logging.mount
        - name: 40-flannel.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
    - name: opt-logging.mount
      command: start
      content: |
        [Unit]
        Description=Mount disk to /opt/logging
        Requires=format-logging-volume.service
        After=format-logging-volume.service

        [Mount]
        What=/dev/xvdh
        Where=/opt/logging
        Type=ext4

        [Install]
        RequiredBy=docker.service
    - name: format-logging-volume.service
      command: start
      content: |
        [Unit]
        Description=Formats logging EBS volume
        After=dev-xvdh.device
        Requires=dev-xvdh.device
        Before=opt-logging.mount

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        Environment="LABEL=opt-logging"
        Environment="DEV=/dev/xvdh"
        # Do not wipe the disk if it's already being used, so the data is persisted across reboots.
        ExecStart=-/bin/bash -c "if ! findfs LABEL=$LABEL > /tmp/label.$LABEL; then wipefs -a -f $DEV && mkfs.ext4 -T news -F -L $LABEL $DEV && echo wiped; fi"

        [Install]
        RequiredBy=opt-logging.mount
    - name: opt-data.mount
      command: start
      content: |
        [Unit]
        Description=Mount disk to /opt/data
        Requires=format-data-volume.service
        After=format-data-volume.service
        Before=docker.service

        [Mount]
        What=/dev/xvdg
        Where=/opt/data
        Type=ext4

        [Install]
        RequiredBy=docker.service
    - name: format-data-volume.service
      command: start
      content: |
        [Unit]
        Description=Formats data EBS volume
        After=dev-xvdg.device
        Requires=dev-xvdg.device
        Before=opt-data.mount

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        Environment="LABEL=opt-data"
        Environment="DEV=/dev/xvdg"
        # Do not wipe the disk if it's already being used, so the docker images are persisted across reboots.
        ExecStart=-/bin/bash -c "if ! findfs LABEL=$LABEL > /tmp/label.$LABEL; then wipefs -a -f $DEV && mkfs.ext4 -T news -F -L $LABEL $DEV && echo wiped; fi"

        [Install]
        RequiredBy=opt-data.mount
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount disk to /var/lib/docker
        Requires=format-docker-volume.service
        After=format-docker-volume.service
        Before=docker.service

        [Mount]
        What=/dev/xvdf
        Where=/var/lib/docker
        Type=ext4

        [Install]
        RequiredBy=docker.service
    - name: format-docker-volume.service
      command: start
      content: |
        [Unit]
        Description=Formats docker EBS volume
        After=dev-xvdf.device
        Requires=dev-xvdf.device
        Before=var-lib-docker.mount

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        Environment="LABEL=var-lib-docker"
        Environment="DEV=/dev/xvdf"
        # Do not wipe the disk if it's already being used, so the docker images are persisted across reboots.
        ExecStart=-/bin/bash -c "if ! findfs LABEL=$LABEL > /tmp/label.$LABEL; then wipefs -a -f $DEV && mkfs.ext4 -T news -F -L $LABEL $DEV && echo wiped; fi"

        [Install]
        RequiredBy=var-lib-docker.mount
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 60-initial-cluster.conf
          content: |
            [Unit]
            Requires=prepare-tls-assets.service
            After=prepare-tls-assets.service

            [Service]
            EnvironmentFile=/var/run/coreos/initial-cluster
    - name: prepare-tls-assets.service
      command: start
      content: |
        [Unit]
        Description=Prepare etcd2 TLS assets
        Before=etcd2.service

        [Service]
        Type=oneshot
        RemainAfterExit=true
        ExecStart=/opt/bin/prepare-tls-assets.sh

        [Install]
        RequiredBy=etcd2.service
    - name: update-engine.service
      command: stop
      enable: false
    - name: locksmithd.service
      command: stop
      enable: false
write_files:
  - path: /etc/environment
    permissions: 0644
    content: |
      COREOS_PUBLIC_IPV4=$public_ipv4
      COREOS_PRIVATE_IPV4=$private_ipv4
  - path: /opt/bin/prepare-tls-assets.sh
    permissions: 0700
    owner: root:root
    content: |
      #!/bin/bash

      mkdir -p /etc/kubernetes/tls
      mv /root/cloudinit/tls/*.pem /etc/kubernetes/tls
  - path: /opt/bin/docker-gc.sh
    permissions: 0700
    owner: root
    content: |
      #!/usr/bin/bash

      /usr/bin/docker rm -v $(docker ps -a -q -f status=exited)
      /usr/bin/docker rmi $(docker images -q -f dangling=true)
      /usr/bin/docker volume rm $(docker volume ls -q -f dangling=true)
  - path: /etc/logrotate.d/docker-containers.conf
    permissions: 0644
    owner: root
    content: |
      /var/lib/docker/containers/*/*.log {
        rotate 5
        copytruncate
        missingok
        notifempty
        compress
        maxsize 10M
        daily
        create 0644 root root
      }
  - path: /opt/bin/kubelet-wrapper.sh
    permissions: 0700
    owner: root:root
    content: |
      #!/usr/bin/bash

      set -e

      if [ ! -f /opt/bin/kubelet ]; then
        mkdir -p /opt/bin
        curl -L -o /opt/bin/kubelet https://s3-us-west-2.amazonaws.com/concur-native-binarys/kubernetes/${kubernetes_version}/kubelet
        chmod 700 /opt/bin/kubelet
      fi

      /opt/bin/kubelet \
        --allow-privileged=true \
        --api-servers=https://${kubernetes_api_dns_name}:443 \
        --register-node=true \
        --cadvisor-port=0 \
        --cluster-domain=cluster.local \
        --cluster-dns=${kubernetes_dns_service_ip} \
        --config=/etc/kubernetes/manifests \
        --cloud-provider=aws \
        --kubeconfig=/etc/kubernetes/node-kubeconfig.yaml \
        --tls-cert-file=/etc/kubernetes/tls/node.pem \
        --tls-private-key-file=/etc/kubernetes/tls/node-key.pem \
        --logtostderr=true \
        --v=2
  - path: /etc/kubernetes/manifests/kube-proxy.yaml
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-proxy
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-proxy
          image: ${kubernetes_hyperkube_image_repo}:${kubernetes_version}
          command:
          - /hyperkube
          - proxy
          - --master=https://${kubernetes_api_dns_name}:443
          - --kubeconfig=/etc/kubernetes/node-kubeconfig.yaml
          - --proxy-mode=iptables
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/tls/certs
              name: "tls-certs"
            - mountPath: /etc/kubernetes/node-kubeconfig.yaml
              name: "kubeconfig"
              readOnly: true
            - mountPath: /etc/kubernetes/tls
              name: "etc-kube-tls"
              readOnly: true
        volumes:
          - name: "tls-certs"
            hostPath:
              path: "/usr/share/ca-certificates"
          - name: "kubeconfig"
            hostPath:
              path: "/etc/kubernetes/node-kubeconfig.yaml"
          - name: "etc-kube-tls"
            hostPath:
              path: "/etc/kubernetes/tls"
  - path: /etc/kubernetes/node-kubeconfig.yaml
    content: |
      apiVersion: v1
      kind: Config
      clusters:
        - name: local
          cluster:
            certificate-authority: /etc/kubernetes/tls/ca-chain.pem
      contexts:
        - context:
            cluster: local
            user: node
          name: node-context
      current-context: node-context
      users:
        - name: node
          user:
            client-certificate: /etc/kubernetes/tls/api-server-client.pem
            client-key: /etc/kubernetes/tls/api-server-client-key.pem
  - path: /etc/kubernetes/manifests/fluentd-es.yaml
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: fluentd-elasticsearch
        namespace: kube-system
        labels:
          k8s-app: fluentd-logging
      spec:
        containers:
        - name: fluentd-elasticsearch
          image: gcr.io/google_containers/fluentd-elasticsearch:1.15
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
        terminationGracePeriodSeconds: 30
        volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
